name: M4shield
author: M4theuskkj | PMMP3 & PMMP4 By frpitu
main: M4Shield\Main
api: 2.0.0
version: 3.0
description: "Um plugin pra proteger servidores de pocketmine 2.0.0 contra grief, bots e outras coisas. Porte Para MCPE 1.16 Por frpitu"